from selenium import webdriver
from selenium.webdriver.common.by import By

options = webdriver.ChromeOptions()

options.add_argument("start-maximized")
options.add_argument('--disable-blink-features=AutomationControlled')
options.add_experimental_option('useAutomationExtension', False)
options.add_experimental_option("excludeSwitches", ['enable-automation'])

driver = webdriver.Chrome(options=options)

"""
driver.execute_script("Object.defineProperty(navigator, 'webdriver', {get: () => undefined})")
driver.execute_cdp_cmd('Network.setUserAgentOverride', {"userAgent": 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.53 Safari/537.36'})
print(driver.execute_script("return navigator.userAgent;"))
"""

driver.get("https://phenotype.pl/")
driver.execute_script('''window.open("https://the100clth.pl/","_blank");''')
driver.execute_script('''window.open("https://animalswave.com/","_blank");''')
driver.execute_script('''window.open("https://relab.store/","_blank");''')
driver.execute_script('''window.open("https://hazel21.com/","_blank");''')
driver.execute_script('''window.open("https://zoology.pl/","_blank");''')
driver.execute_script('''window.open("https://premieresociety.com/pl/","_blank");''')
driver.execute_script('''window.open("https://hillswear.com/","_blank");''')
driver.execute_script('''window.open("https://www.snipes.pl/","_blank");''')
driver.execute_script('''window.open("https://www.alexanderbigwig.com/","_blank");''')
driver.execute_script('''window.open("https://inrablew.pl/pl/","_blank");''')
driver.execute_script('''window.open("https://mindstate.pl/pl/","_blank");''')
driver.execute_script('''window.open("https://zillamob.com/","_blank");''')
driver.execute_script('''window.open("https://majors.pl/","_blank");''')
driver.execute_script('''window.open("https://rareeverywhere.pl/","_blank");''')
driver.execute_script('''window.open("https://ideologyproject.com/store/","_blank");''')
driver.execute_script('''window.open("https://enragecustoms.pl/shop/","_blank");''')
driver.execute_script('''window.open("https://an-appendage.com/?v=9b7d173b068d&c=2a7c42566189","_blank");''')
driver.execute_script('''window.open("https://www.7more7.com/","_blank");''')
driver.execute_script('''window.open("https://velpa.pl/","_blank");''')
driver.execute_script('''window.open("https://debrande.pl/","_blank");''')
driver.execute_script('''window.open("https://www.gugushop.pl/","_blank");''')
driver.execute_script('''window.open("https://www.reserved.com/pl/pl/","_blank");''')
driver.execute_script('''window.open("https://www.zara.com/pl/","_blank");''')
driver.execute_script('''window.open("https://www.vangraaf.com/pl/","_blank");''')
driver.execute_script('''window.open("https://www.vitkac.com/pl","_blank");''')
driver.execute_script('''window.open("https://www.zalando-lounge.pl/event#","_blank");''')
driver.execute_script('''window.open("https://www.moliera2.com/","_blank");''')
driver.execute_script('''window.open("https://gomez.pl/pl/dla_niego","_blank");''')
driver.execute_script('''window.open("https://modivo.pl/m/mezczyzni.html","_blank");''')
driver.execute_script('''window.open("https://www.guess.eu/pl-pl/homepage","_blank");''')
driver.execute_script('''window.open("https://www.asos.com/pl/mezczyzni/","_blank");''')
driver.execute_script('''window.open("https://www.forpro.pl/","_blank");''')
driver.execute_script('''window.open("https://www.aboutyou.pl/","_blank");''')
driver.execute_script('''window.open("https://www.ataf.pl/pl/","_blank");''')
driver.execute_script('''window.open("https://www.nike.com/pl/","_blank");''')
driver.execute_script('''window.open("https://www.adidas.pl/","_blank");''')
driver.execute_script('''window.open("https://answear.com/c/on","_blank");''')
driver.execute_script('''window.open("https://www.peek-cloppenburg.pl/mezczyzni/","_blank");''')
driver.execute_script('''window.open("https://skstore.eu/pl","_blank");''')
driver.execute_script('''window.open("https://streetsupply.pl/","_blank");''')
driver.execute_script('''window.open("https://www.mandmdirect.pl/","_blank");''')
driver.execute_script('''window.open("https://worldbox.pl/","_blank");''')
driver.execute_script('''window.open("https://streetstyle24.pl/","_blank");''')
driver.execute_script('''window.open("https://eastendshop.com/pl/men-landing","_blank");''')
driver.execute_script('''window.open("https://runcolors.pl/","_blank");''')
driver.execute_script('''window.open("https://www.luisaviaroma.com/","_blank");''')
driver.execute_script('''window.open("https://warsawsneakerstore.com/","_blank");''')
driver.execute_script('''window.open("https://www.caliroots.com/pl","_blank");''')

